"""
Alert Publisher — sends enriched fraud alerts via AWS SNS and SES.
Formats alert payloads with full context for fraud operations team.
Pramod Vishnumolakala — github.com/pramod-vishnumolakala
"""

import json
import logging
import boto3
from datetime import datetime, timezone
from dataclasses import dataclass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

SNS_TOPIC_ARN  = "arn:aws:sns:us-east-1:123456789:fraud-alerts"
SES_FROM_EMAIL = "fraud-alerts@pramod-dataplatform.com"
SES_TO_EMAILS  = ["fraud-ops@pramod-dataplatform.com", "pramodvishnumolakala@gmail.com"]
REGION         = "us-east-1"

SEVERITY_MAP = {
    range(60,  70):  ("LOW",      "🟡"),
    range(70,  85):  ("MEDIUM",   "🟠"),
    range(85,  100): ("HIGH",     "🔴"),
    range(100, 201): ("CRITICAL", "🚨"),
}


def get_severity(score: int) -> tuple[str, str]:
    for score_range, (label, emoji) in SEVERITY_MAP.items():
        if score in score_range:
            return label, emoji
    return "HIGH", "🔴"


@dataclass
class AlertPayload:
    transaction_id: str
    account_id:     str
    amount:         float
    timestamp:      str
    risk_score:     int
    signals:        list[dict]
    merchant_id:    str = ""
    merchant_category: str = ""
    merchant_country:  str = ""


class AlertPublisher:
    """
    Publishes fraud alerts to SNS topic and SES email.
    Called by FraudDetector when risk_score >= threshold.
    """

    def __init__(self):
        self.sns = boto3.client("sns", region_name=REGION)
        self.ses = boto3.client("ses", region_name=REGION)

    def publish(self, payload: AlertPayload):
        severity, emoji = get_severity(payload.risk_score)
        self._publish_sns(payload, severity, emoji)
        self._send_email(payload, severity, emoji)
        logger.info(
            f"Alert published | txn={payload.transaction_id} "
            f"severity={severity} score={payload.risk_score}"
        )

    def _publish_sns(self, payload: AlertPayload, severity: str, emoji: str):
        message = {
            "alert_type":      "FRAUD_DETECTED",
            "severity":        severity,
            "transaction_id":  payload.transaction_id,
            "account_id":      payload.account_id,
            "amount":          f"${payload.amount:,.2f}",
            "risk_score":      payload.risk_score,
            "signals":         payload.signals,
            "merchant_id":     payload.merchant_id,
            "merchant_category": payload.merchant_category,
            "merchant_country":  payload.merchant_country,
            "timestamp":       payload.timestamp,
            "alert_generated_at": datetime.now(timezone.utc).isoformat(),
        }
        try:
            self.sns.publish(
                TopicArn=SNS_TOPIC_ARN,
                Subject=f"{emoji} FRAUD ALERT [{severity}] — Account {payload.account_id}",
                Message=json.dumps(message, indent=2),
                MessageAttributes={
                    "severity": {
                        "DataType":    "String",
                        "StringValue": severity,
                    },
                    "risk_score": {
                        "DataType":    "Number",
                        "StringValue": str(payload.risk_score),
                    },
                },
            )
        except Exception as exc:
            logger.error(f"SNS publish failed: {exc}")

    def _send_email(self, payload: AlertPayload, severity: str, emoji: str):
        signals_html = "".join(
            f"<tr><td>{s['rule']}</td><td>{s['score']}</td><td>{s['detail']}</td></tr>"
            for s in payload.signals
        )
        body_html = f"""
        <html><body style="font-family:Arial,sans-serif;max-width:600px">
        <h2 style="color:#d32f2f">{emoji} Fraud Alert — {severity}</h2>
        <table border="1" cellpadding="8" style="border-collapse:collapse;width:100%">
          <tr><td><b>Transaction ID</b></td><td>{payload.transaction_id}</td></tr>
          <tr><td><b>Account ID</b></td><td>{payload.account_id}</td></tr>
          <tr><td><b>Amount</b></td><td>${payload.amount:,.2f}</td></tr>
          <tr><td><b>Risk Score</b></td><td>{payload.risk_score}</td></tr>
          <tr><td><b>Merchant</b></td><td>{payload.merchant_id} ({payload.merchant_category}, {payload.merchant_country})</td></tr>
          <tr><td><b>Timestamp</b></td><td>{payload.timestamp}</td></tr>
        </table>
        <h3>Triggered Rules</h3>
        <table border="1" cellpadding="8" style="border-collapse:collapse;width:100%">
          <tr style="background:#f5f5f5"><th>Rule</th><th>Score</th><th>Detail</th></tr>
          {signals_html}
        </table>
        <p style="color:#666;font-size:12px">Generated by Fraud Detection Pipeline — Pramod Vishnumolakala</p>
        </body></html>
        """
        try:
            self.ses.send_email(
                Source=SES_FROM_EMAIL,
                Destination={"ToAddresses": SES_TO_EMAILS},
                Message={
                    "Subject": {"Data": f"{emoji} Fraud Alert [{severity}] — {payload.account_id}"},
                    "Body":    {"Html": {"Data": body_html}},
                },
            )
        except Exception as exc:
            logger.error(f"SES send failed: {exc}")
